nacos:
  config:
    auto-refresh: true
    data-id: gradle_demo.yaml
    password: nacos
    username: nacos
    server-addr: 120.24.36.55:8848

rocketmq:
  name-server: 120.24.36.55:9876
  producer:
    group: spring-boot-group
    retry-times-when-send-failed: 10
    send-message-timeout: 10000



spring:
  # 引擎模板配置
  thymeleaf:
    cache: false # 关闭缓存
    mode: HTML # 去除htm5严格校验
    prefix: classpath:/templates/ # 指定 thymeleaf 模板路径
    encoding: UTF-8 # 指定字符集编码
  mvc:
    static-path-pattern: /static/** # js ,css 等静态文件路径
  application:
    name: nacos-demo
  cache:
    type: redis
  devtools:
    restart:
      enabled: true
  freemarker:
    checkTemplateLocation: false
#    redis快照关闭了导致不能持久化的问题
#  stop-writes-on-bgsave-error no
  redis:
    host: 120.24.36.55
    port: 6379
    database: 0
    password: 987654321
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    redisson:
      file: classpath:redisson.yml




