nacos:
  config:
    auto-refresh: true
    data-id: gradle_demo.yaml
    password: nacos
    server-addr: 120.24.36.55:8848
    username: nacos
spring:
  application:
    name: nacos-demo
  cache:
    type: redis
  devtools:
    restart:
      enabled: true
  freemarker:
    checkTemplateLocation: false
  redis:
    database: 0
    password: 987654321
    host: 120.24.36.55
    port: 6379
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    redisson:
      file: classpath:redisson.yml



