#实体扫描
#Mybatis-plus:
#  typeAliasesPackage: com.xxx.project.biz.*.entity,com.xxx.project.biz.*.*.entity

#nacos:
#  config:
#    auto-refresh: true
#    data-id: gradle_demo.yaml
#    password: nacos
#    username: nacos
#    server-addr: 120.24.55.36:8848

mybatis-plus:
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      db-type: MYSQL
      field-strategy: NOT_EMPTY
      id-type: auto
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://120.24.36.55:3306/rbac?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
  # 引擎模板配置
  thymeleaf:
    cache: false # 关闭缓存
    mode: HTML # 去除htm5严格校验
    prefix: classpath:/templates/ # 指定 thymeleaf 模板路径
    encoding: UTF-8 # 指定字符集编码
  mvc:
    static-path-pattern: /static/** # js ,css 等静态文件路径
  application:
    name: nacos-demo
  cache:
    type: redis
  devtools:
    restart:
      enabled: true
  freemarker:
    checkTemplateLocation: false
  redis:
    database: 0
    password: 987654321
    host: 120.24.36.55
    port: 6379
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    redisson:
      file: classpath:redisson.yml




